<?php

namespace App\Services;

use App\Criterias\AppRequestCriteria;
use App\Criterias\FilterByPatientIdCriteria;
use App\Repositories\ScreeningRepository;

/**
 * ScreeningService
 */
class ScreeningService extends AppService
{
    /**
     * @var ScreeningRepository
     */
    protected $repository;

    /**
     * @param ScreeningRepository $repository
     */
    public function __construct(ScreeningRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @param int $limit
     * @return mixed
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function all($limit = 20)
    {
        return $this->repository
            ->resetCriteria()
            ->pushCriteria(app(FilterByPatientIdCriteria::class))
            ->pushCriteria(app(AppRequestCriteria::class))
            ->paginate($limit);
    }

    /**
     * @param array $data
     * @param $id
     * @param bool $skipPresenter
     * @return array|mixed
     */
    public function update(array $data, $id, bool $skipPresenter = false)
    {
        if ($data['imc'] === 'null') $data['imc'] = 0;
        return parent::update($data, $id, $skipPresenter); // TODO: Change the autogenerated stub
    }

}
