services:
  app-clinic:
    image: legacy-api_legacy-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8001:80
    networks:
      - verbrechen
networks:
  verbrechen:
    external: true
    name: gewinnspiel-docker_verbrechen
