sonar.projectKey=madeiramadeirabr_service-omni-hub-api
sonar.organization=madeiramadeirabr
sonar.exclusions=.idea/**,node/**,bin/**,tmp/**,vendor/**,build/**,dist/**,libs/**,test/**,.vscode/**,coverage/**,.git/**
