name: Coordinate Workflows (CI)
on:
  push:
    branches:
      - production
      - staging
      - qa-workflow
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  quality-assurance:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      coverage-path: coverage.xml

  information-security:
    needs: quality-assurance
    name: information-security
    uses: ./.github/workflows/infosec.yml
    with:
      coverage-path: coverage.xml
    secrets: inherit