name: Information Quality Assurance Tests Validators

on:
  workflow_call:
    inputs:
      coverage-path:
        required: false
        type: string

jobs:
    quality-assurance:
      name: tests-validators
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mongodb, rdkafka

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y libmongoc-1.0-0 libmongoc-dev librdkafka-dev
            composer install --no-interaction --prefer-dist

        - name: Check Composer Platform Requirements
          run: composer check-platform-reqs

        - name: Run Tests
          run: php artisan test ./tests/Unit --coverage

